name: CI for React Native Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v3

 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: node server.js
      - name: Run Jest tests
        run: npm test
